# Generated by Django 3.1.1 on 2020-09-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200908_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='datee',
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
